name: conformer
seed: 42
output_dir: ./out

preprocess:
  mode: normal
  tokenizer:
    mode: pp_add
  wav_dir: ../../jsut/jsut_ver1.1/basic5000/wav
  label_dir: ../../jsut/jsut-label/labels/basic5000
  output_dir: ../../dataset/pp_add
  orig_sr: 48000
  new_sr: 24000

train:
  batch_size: 16
  num_epochs: 1000
  monitor: valid/recon
  save_interval: 100

data:
  data_dir: ../../dataset/pp_add
  valid_size: 100
  tokenizer:
    mode: pp_add

model:
  n_mel: 80

  embedding:
    mode: pp_add
    n_phoneme: 45
    n_prosody: 8
    channels: 192

  encoder:
    channels: 192
    n_heads: 2
    n_layers: 6
    dropout: 0.1

  variance_adopter:
    in_channels: 192
    channels: 256
    dropout: 0.1

  decoder:
    channels: 192
    n_heads: 2
    n_layers: 6
    kernel_size: 7
    dropout: 0.1

optimizer:
  lr: 1.0
  betas: [0.9, 0.98]

scheduler:
  mode: noam
  warmup_steps: 4000
  channels: 192

